# Generated by Django 5.1.4 on 2026-07-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('technical', 'Technical Training'), ('operations', 'Operations & Outreach'), ('admin', 'Administration'), ('other', 'Other')], default='technical', max_length=50)),
                ('location', models.CharField(default='ECIL X Road, Hyderabad', max_length=100)),
                ('experience', models.CharField(default='2+ Years', max_length=50)),
                ('description', models.TextField(help_text='Detailed job description and responsibilities')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
