# Generated by Django 5.1.4 on 2026-07-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_jobopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
