# Generated by Django 5.1.4 on 2026-07-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_galleryitem_category_galleryitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Auto-updated when course is saved'),
        ),
    ]
