# Generated by Django 5.1.4 on 2026-07-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_add_updated_at_to_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
