# Generated by Django 5.1.4 on 2026-07-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended resolution: 800x600 pixels', null=True, upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='file',
            field=models.FileField(help_text='Upload media (Recommended 1080x1080 for images)', upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload banner image (Recommended 1920x1080)', null=True, upload_to='banners/images/'),
        ),
    ]
