# Generated by Django 5.1.4 on 2026-07-28 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_course_image_alter_galleryitem_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='Executive working on this enquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_enquiries', to=settings.AUTH_USER_MODEL),
        ),
    ]
