# Generated by Django 5.1.4 on 2026-10-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_enquiry_claimed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the director', max_length=150)),
                ('designation', models.CharField(default='Managing Director', help_text='Title shown as the card heading (e.g. Managing Director)', max_length=200)),
                ('desk_label', models.CharField(default='Welcome Message', help_text='Sub-label shown below the designation (e.g. Welcome Message)', max_length=200)),
                ('message', models.TextField(help_text='Short message / quote displayed on the director card')),
                ('photo', models.ImageField(blank=True, help_text='Portrait photo (Recommended: 360×580 px)', null=True, upload_to='directors/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Cards are sorted by this value (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this director from the About page')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
